#ifndef ABSTRACTASYNCCLIENT_GLOBAL_H
#define ABSTRACTASYNCCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ABSTRACTASYNCCLIENT_LIBRARY)
#  define ABSTRACTASYNCCLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ABSTRACTASYNCCLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ABSTRACTASYNCCLIENT_GLOBAL_H
